
# 1. 繳款關鍵字 (使用者 -> 銀行)
payment_keywords:
  - '網路銀行繳款'
  - '自動扣繳'
  - '本行繳款'
  - '轉帳扣繳'
  - '轉帳繳款'
  - '本行扣繳'
  - '網銀行動繳'
  - 'ATM轉帳'
  - '匯款'
  - 'Payment Thank You'

# 2. 折抵/紅利關鍵字 (銀行 -> 使用者)
credit_keywords:
  - '刷卡金'
  - 'e point' #玉山銀行的紅利折抵服務
  - '回饋'    # 現金回饋
  - '紅利'    # 紅利折抵
  - '折抵'
  - '回饋金'
  - '點數'    # 點數折抵
  - '調整'    # 通常是銀行端的帳務調整
  - 'OFF SET' # 外商銀行常見
  - '加碼'
  - '支付碳帳戶' # 玉山銀行的綠色回饋計畫
  - '小樹點折抵' # 國泰世華銀行在清洗時新增的關鍵字

# 3. 銀行費用 (銀行 -> 使用者)
fee_keywords:
  - '手續費'
  - '服務費'
  - '年費'
  - '利息'
  - '違約金'
  - '滯納金'
  - '調整'    # 通常是銀行端的帳務調整